cloud:
  aws:
    credentials:
      access-key: AKIATRQ2VEL43K6IZWGD
      secret-key: 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
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: siu-bucket

amazon:
  dynamodb:
    endpoint: dynamodb.ap-northeast-1.amazonaws.com

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 9090
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: test123
    key-alias: spring
